POST http://localhost:8000/api/add-device HTTP/1.1
Content-Type: application/json
Cookie: key=first-value

{
	"label": "Android TV Uherský Brod",
	"description": "TV umístěna na obchodním oddělení pro zobrazení kalendáře",
	"ip_address": "192.168.2.36",
    "uuid": "ef3c5fe116d18af9",
    "location_id": 3,
    "api_key": "qaxYuEEUBUAviu2EUyfN5RNcXvTfMSYZ"
}